### ISSUE TITLE
Error when using dataZoom with filterMode: 'filter' in official example (v5.3.0 and higher)

### ISSUE THREAD

**Issue by mjurika** [xieziyu/ngx-echarts#352]
## Repro steps

1. Open example: https://echarts.apache.org/examples/en/editor.html?c=custom-cartesian-polygon&lang=js&version=5.3.1
2. Change `filterMode: 'none'` at line#19 to `filterMode: 'filter'` (this is default).
3. Zoom in.
4. Error in console: 
```
Uncaught TypeError: Cannot read properties of undefined (reading '__ec_inner_28')
    at echarts.min.js:45:10441
    at t._remove (echarts.min.js:45:667415)
    at t._executeOneToOne (echarts.min.js:45:223865)
    at t.execute (echarts.min.js:45:223447)
    at e.render (echarts.min.js:45:667510)
    at t.progress (echarts.min.js:45:166606)
    at t._doProgress (echarts.min.js:45:135145)
    at t.perform (echarts.min.js:45:134717)
    at echarts.min.js:45:215693
    at e.<anonymous> (echarts.min.js:45:116154)
```

**Comment by mjurika** [comment]
I also have this issue when updating custom series with `eChart.setOption(options)`. Because of this issue I can't update echarts to 5.3.x in my project.
