### ISSUE TITLE
init is not a function

### ISSUE THREAD

**Issue by aubweb9** [xieziyu/ngx-echarts#434]
Hello,

I just updated my project from Angular 17 to 18 (same for ngx-echarts) and I am now facing this error : 
```
ERROR TypeError: init is not a function
    at /node_modules/ngx-echarts/fesm2022/ngx-echarts.mjs:211:13
    at _ZoneDelegate.invoke /node_modules/zone.js/fesm2015/zone.js:369:28)
    at ZoneImpl.run (/node_modules/zone.js/fesm2015/zone.js:111:43)
    at /node_modules/zone.js/fesm2015/zone.js:2538:40
    at _ZoneDelegate.invokeTask (/node_modules/zone.js/fesm2015/zone.js:402:33)
    at ZoneImpl.runTask /node_modules/zone.js/fesm2015/zone.js:159:47)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.js:482:23) {stack: 'TypeError: init is not a function
    at http…e (http://localhost:4200/polyfills.js:482:23)', message: 'init is not a function'}
```

in my ngModule imports I have 
`NgxEchartsModule.forRoot({
            echarts: () => import('echarts')
        })`

And in my component I do the usual 
`import { EChartsOption } from 'echarts';
import * as echarts from 'echarts';`

Any idea of what could have gone wrong during the update ?

Thanks.

**Comment by aubweb9** [comment]
Adding provideEcharts(), in the module of the providers section, solves this problem.
